### ISSUE TITLE
Atualizar o arquivo de familia de fontes | Update the font-family file

### ISSUE THREAD

**Issue by marcellecode** [Engenheira-Coelho/O-que-as-mulheres-de-tech-querem#15]
Atualizar o arquivo de familia de fontes | Update the font-family file

<details>
<summary>English version</summary>

Update the font-family file

- The file should be: **general/fontFamily.js**
- Implement this as a constant.

Check-list:

- [ ] Access the file or create.
- [ ] Insert the new constant as Figma indicates.
- [ ] Send your PR.

</details>
<details>
<summary>Versão em português</summary>

Atualizar o arquivo da família de fontes

- O arquivo deve ser: **general/fontFamily.js**
- Implemente os valores como constantes.

Check-list:
- [ ] Acesse o arquivo ou crie.
- [ ] Insira a nova constante como indica o Figma.
- [ ] Envie seu PR.

</details>

FIGMA: https://www.figma.com/file/7vZzUVZZ4kJHUSv0dDIItv/BeeStrong_Design?node-id=1%3A18

**Comment by engenheiracoelho** [comment]
Thanks @nailabb ! 

Amazing work!
