### ISSUE TITLE
Crie um efeito quando o mouse passar no cartão | Create an effect when the mouse hovers over the card

### ISSUE THREAD

**Issue by engenheiracoelho** [Engenheira-Coelho/O-que-as-mulheres-de-tech-querem#16]
Crie um efeito quando o mouse passar no cartão | Create an effect when the mouse hovers over the card

<details>
<summary>English version</summary>

Create a hover effect when the mouse hovers over the card. 

**In the image you can see the 2 options for the card:**

**1 -** Card with the principal image, which is a prop on the component receiving the data from the situations.json (SITUATIONS[i].image).

**2 -** Card with the description text, which is a prop on the component receiving the data from the situations.json (SITUATIONS[i].description). The hover should have the same color as the image, which should be available on (SITUATIONS[i].color).

The file situations.json should have the following structure:
```
{  
  SITUATIONS: [
    {
      id:1,
      description: "ABC",
      image: "path",
      image-description: "ABC",
      color: "#DF6B3C"
    },
    {
      id:2,
      description: "ABC",
      image: "path",
      image-description: "ABC",
      color: "#0A455E"
    }
  ]
}
```

Check-list:

- [ ] Access the card component.
- [ ] Insert the hover verification.
- [ ] On the hover, insert the description label.
- [ ] On the hover, insert the CSS specifications.
- [ ] Verify if all your images are showing ok.
- [ ] Verify if you don't have any inconsistency on the CSS.
- [ ] Send your PR.

</details>
<details>
<summary>Versão em português</summary>

Crie um efeito quando o mouse passar sobre o cartão.

**Na imagem você pode ver as 2 opções para o cartão:**

**1 -** Cartão com a imagem principal, que é uma prop do componente que recebe os dados do arquivo situations.json (SITUATIONS[i].image).

**2 -** Cartão com o texto descritivo, que é uma propriedade do componente que recebe os dados das situações.json (SITUATIONS[i].description). O hover deve ter a mesma cor da imagem, que deve estar disponível em (SITUATIONS[i].color).

O arquivo situações.json deve ter a seguinte estrutura:

```
{  
  SITUATIONS: [
    {
      id:1,
      description: "ABC",
      image: "path",
      image-description: "ABC",
      color: "#DF6B3C"
    },
    {
      id:2,
      description: "ABC",
      image: "path",
      image-description: "ABC",
      color: "#0A455E"
    }
  ]
}
```

Check-list:

- [ ] Crie o novo componente.
- [ ] Crie o arquivo json com alguns exemplos.
- [ ] No componente você provavelmente poderia usar uma função map para chamar o componente card e usar o arquivo de situações.
- [ ] Insira o CSS para limitar a linha para mostrar 3 cartões.
- [ ] Verifique se todas as suas imagens estão aparecendo bem.
- [ ] Envie seu PR.

</details>

![Screen Shot 2022-10-11 at 19 58 27](https://user-images.githubusercontent.com/13292181/195225794-54e01c70-de4a-4934-9b74-8e6591fe9372.png)

**Comment by marcellecode** [comment]
Sugestão de codigo para iniciar:

.card:hover {
background-color: rgba(182, 121, 109, 0.5);
display: flex;
}

.card:hover .title{
display: none;
}

.card:hover .comment {
display: flex;
color: black;
width: 250px;
height: 250px;
background-color: rgba(182, 121, 109, 0.5);
font-weight: bold;
align-items: inherit;
}

**Comment by marcellecode** [comment]
Pending:  
- fix align text  
- custom hover with React

**Comment by engenheiracoelho** [comment]
Thanks @marcellecode to solve this one
