### ISSUE TITLE
Atualizar o arquivo de cores | Update the colors file

### ISSUE THREAD

**Issue by engenheiracoelho** [Engenheira-Coelho/O-que-as-mulheres-de-tech-querem#17]
Atualizar o arquivo de cores | Update the colors file

<details>
<summary>English version</summary>

Update the palette file

- The file should be: **general/palette.js**
- Implement this as a constant.

Check-list:

- [ ] Access the file or create.
- [ ] Insert the new constant as Figma indicates.
- [ ] Send your PR.

</details>
<details>
<summary>Versão em português</summary>

Atualizar o arquivo da paleta de cores 

- O arquivo deve ser: **general/palette.js**
- Implemente os valores como constantes.

Check-list:
- [ ] Acesse o arquivo ou crie.
- [ ] Insira a nova constante como indica o Figma.
- [ ] Envie seu PR.

</details>

FIGMA: https://www.figma.com/file/7vZzUVZZ4kJHUSv0dDIItv/BeeStrong_Design?node-id=1%3A18

**Comment by PaolaDaft** [comment]
Hi✨, the issue confused me a little, I should add the color palette to work, but why in a new .js file and not in the index.css that the project already has?, that causes me doubt.

✉️Thank you very much for your answer, I am a beginner and it is my first time trying to collaborate in open source projects.

**Comment by engenheiracoelho** [comment]
Thanks @PaolaDaft !

We are really happy with your contribution!
